# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: ISU AMS - Iowa State University Student Chapter of the American Meteorological Society
email: webmaster.isuams@iastate.edu
description: > # this means to ignore newlines until "baseurl:"
  The Iowa State University Student Chapter of the American Meteorological Society
  (ISU AMS) is an award-winning chapter committed to community outreach and student
  involvement in social and academic activities.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: isuams
github_username:  jthielen

# Addt'n Config
permalink: pretty

# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
  - instructions.md

# Sass Settings
sass:
  sass_dir: _sass

# Misc Config
recent_posts_limit: 5
